Week25までの処理更新
posse-ap/sample-ph2-website pull request #10
Opened 2023-11-08 07:46 UTC by kohei23n

# 対応内容

- コメントにて記載

2023-11-08 07:47 UTC, kohei23n commented on src/admin/index.php
> +      $pdo->beginTransaction();
本は beginTransaction を try の中に書いてたから揃えた。
実際 rollback が catch の中なのに begin が外にあるのは違和感あった。

2023-11-08 07:48 UTC, kohei23n commented on src/admin/questions/edit.php
> +session_start();
これがないと、このページに飛んだ途端ログイン画面に遷移してしまうため追加した。

2023-11-08 07:48 UTC, kohei23n commented on src/admin/questions/create.php
> +session_start();
ここはなくても login.php に遷移されないけど、統一するために追記。なんでだ？

2023-11-08 07:54 UTC, kohei23n commented on src/admin/questions/edit.php
全体的にめっちゃ変えちゃってますが、こっちの方が理解しやすい気がしてます！

差分見てもあまりわからない気がするので transaction 内の流れざっと説明します：

1. questions テーブルの画像の更新
2. questions テーブルの画像以外の更新
3. choices テーブルの更新

1 と 2 を完全に切り分けて、2 → 1 の順番で実装しましょう、って指定してます。また、トランザクション処理をインプットの方でも例として挙げてるので、それを参考にすればある程度自走できるかな〜って思ってます。

2023-11-08 07:57 UTC, kohei23n commented on src/admin/questions/edit.php
> -        <form action="../../services/update_question.php" class="question-form" method="POST" enctype="multipart/form-data">
他のファイルは action 指定してないから統一。「指定していない場合は、そのコードが書かれているファイルを参照する」って補足は一応 Week24 のインプットに追加済み。

2023-11-08 07:57 UTC, kohei23n commented on src/admin/questions/edit.php
> +            </div>
この辺りは、見た目の整形。選択肢横並びにして画面からはみ出ないようにしてるとか。

2023-11-08 07:58 UTC, kohei23n commented on src/assets/img/quiz/1590376685638c2951beab74.09772806.JPG
画像です。画像の編集機能をテストしたときに残したままだったものかな？

2023-11-09 05:57 UTC, kohei23n commented on src/admin/auth/signin.php
バリデーション処理の追記

2023-11-09 05:58 UTC, kohei23n commented on src/admin/index.php
> +    } catch (PDOException $e) {
PDOException が一般的だと出てきた。本もそっちで書いてるみたい。

2023-11-09 05:59 UTC, kohei23n commented on src/admin/questions/create.php
> +session_start();
SESSION周りのコード抜けたので追記

2023-11-09 06:00 UTC, kohei23n commented on src/admin/questions/edit.php
> +        if ($_FILES['image']['error'] != UPLOAD_ERR_OK) {
create.php と同じようにバリデーション追記

2023-11-10 09:39 UTC, bigdragon0610 requested changes
見ました〜

2023-11-10 09:39 UTC, bigdragon0610 commented on src/admin/auth/signin.php
> +  } elseif (!filter_var($_POST['email'], FILTER_VALIDATE_EMAIL)) {
elseif と else if どっちかにしたい

2023-11-10 09:39 UTC, bigdragon0610 commented on src/admin/auth/signin.php
> +            <p style="color: red;"><?= htmlspecialchars($message) ?></p>
htmlspecialcharsいらないかも

2023-11-10 09:39 UTC, bigdragon0610 commented on src/admin/questions/create.php
> +      die("ファイルがアップロードされていない、またはアップロードでエラーが発生しました。");
dieはちょっとエラーハンドリングと呼べない代物な気がする
処理止まっちゃうから…

2023-11-10 09:39 UTC, bigdragon0610 commented on src/admin/questions/create.php
> +    $pdo = new PDO('mysql:host=db;dbname=posse', 'root', 'root');
そういえばここでpdo定義するんだっけ？
ファイル分けしてないのか

2023-11-13 04:03 UTC, kohei23n commented on src/admin/auth/signin.php
> +            <p style="color: red;"><?= htmlspecialchars($message) ?></p>
https://github.com/posse-ap/sample-ph2-website/pull/10/commits/1db82b9c132350918e6e5a2d82c31fe02e5e30b1

2023-11-13 04:05 UTC, kohei23n commented on src/admin/auth/signin.php
> +  } elseif (!filter_var($_POST['email'], FILTER_VALIDATE_EMAIL)) {
https://github.com/posse-ap/sample-ph2-website/pull/10/commits/c019746cd5910994f610f87f7aabc47fbb3d29b4

vendor に入ってたファイルが elseif 使ってたからそっちに統一

2023-11-13 04:16 UTC, kohei23n commented on src/admin/questions/create.php
> +      die("ファイルがアップロードされていない、またはアップロードでエラーが発生しました。");
https://github.com/posse-ap/sample-ph2-website/pull/10/commits/f3da30d6306e3b54238543a3de665e2a557dd957

2023-11-17 09:44 UTC, bigdragon0610 commented on src/admin/questions/create.php
> +      error_log($e->getMessage());
セッションにエラーメッセージを格納して、
元の画面では、エラーがセッションに格納されてたら表示するようにしたらよさそう
以下はGPT
```php
# create.php
$_SESSION['error'] = 'エラーメッセージ';
```

```php
# 元の画面
if (isset($_SESSION['error'])) {
    echo "<p>" . $_SESSION['error'] . "</p>";
    unset($_SESSION['error']); // エラーメッセージをクリア
}
```

2023-11-24 11:11 UTC, bigdragon0610 approved these changes
LGTM!!!

2023-11-24 11:11 UTC, merged